### ISSUE TITLE
Upload or submit as third party mod to curseforge

### ISSUE THREAD

**Issue by itsdinkd** [Up-Mods/Soulbound#2]
Please upload to curseforge so we can add to our modpacks. 

Thanks!

**Comment by UpcraftLP** [comment]
So for some reason I didn't get a notification for this, sorry about that.

Anyway, I am in the process of sorting that out, just waiting for Overwolf support to get back to me.

**Comment by itsdinkd** [comment]
no worries! I've already submitted it for ya.
