### ISSUE TITLE
1.20.1 Update halted by Actions

### ISSUE THREAD

**Issue by adaliszk** [Up-Mods/Soulbound#6]
Hey! Thank you very much for continuing on an archived project!

From the looks, the 1.20 branch was working, but when the trunk ran the Action for publishing, it failed on authentication issues. Please take a look and upload a version. 😉

**Comment by UpcraftLP** [comment]
Hey o/
somehow I didn't get a notification for this issue -.-

Yes the deployment failed because I had forgotten to update the API keys so I did that manually. It's been published on both CurseForge and Modrinth this entire time tho?

**Comment by adaliszk** [comment]
Thank you very much for fixing it!
